ALTER TABLE merch_rules ADD COLUMN IF NOT EXISTS fired_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE merch_rules ADD COLUMN IF NOT EXISTS last_fired_at TIMESTAMP;
ALTER TABLE click_events ADD COLUMN IF NOT EXISTS product_price DOUBLE PRECISION;
